---
# Task file for rootless acmetool setup

- name: Create "{{acmetool_user}}" user for acmetool
  user:
    name: "{{acmetool_user}}"
    # group: "{{acmetool_user}}"
    create_home: false
    shell: "/usr/sbin/nologin"

- name: Create /var/lib/acme and set permissions
  file:
    path: "/var/lib/acme"
    owner: "{{acmetool_user}}"
    group: "{{acmetool_user}}"
    state: "directory"

- name: Run handler
  meta: flush_handlers

- name: Create /usr/lib/acme/hooks and set permissions
  file:
    path: "/usr/lib/acme/hooks"
    owner: "root"
    group: "{{acmetool_user}}"
    mode: "0775"
    state: "directory"

- name: Get files in hook
  find:
    path: "/usr/lib/acme/hooks"
    file_type: file
    recurse: true
  register: hook_files

- name: Lookdown hooks dir
  file:
    path: "{{ item.path }}"
    owner: "root"
    group: "root"
    mode: u+s,g=rX
  with_items:
    - "{{ hook_files.files }}"

- name: Setup NOPASSWD for /usr/lib/acme/hooks
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: "^# User priviledge"
    line: "{{acmetool_user}} ALL=(root) NOPASSWD: /usr/lib/acme/hooks/"
